[2025-06-06 14:01:16,768][tsl][INFO] - Fit and set scaler for target: StandardScaler(bias=(1, 1, 1), scale=(1, 1, 1))
[34m[1mwandb[0m: wandb.init() called while a run is active and reinit is set to 'default', so returning the previous run.
GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
HPU available: False, using: 0 HPUs
`Trainer(limit_train_batches=1.0)` was configured so 100% of the batches per epoch will be used..
/home/mnogales/miniconda3/envs/taming-env/lib/python3.10/site-packages/pytorch_lightning/callbacks/model_checkpoint.py:617: UserWarning: Checkpoint directory logs/dcrnn/ostrinia/2025-06-06/14-01-14 exists and is not empty.
  rank_zero_warn(f"Checkpoint directory {dirpath} exists and is not empty.")
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

  | Name          | Type             | Params
---------------------------------------------------
0 | loss_fn       | MaskedMAE        | 0
1 | train_metrics | MetricCollection | 0
2 | val_metrics   | MetricCollection | 0
3 | test_metrics  | MetricCollection | 0
4 | model         | DCRNNModel       | 141 K
---------------------------------------------------
141 K     Trainable params
0         Non-trainable params
141 K     Total params
0.566     Total estimated model params size (MB)
Sanity Checking DataLoader 0:   0%|                                                                                                                                                                                                                               | 0/2 [00:00<?, ?it/s][2025-06-06 14:01:18,048][tsl][WARNING] - Only args ['edge_index', 'x', 'edge_weight'] are forwarded to the model (DCRNNModel).
/home/mnogales/miniconda3/envs/taming-env/lib/python3.10/site-packages/pytorch_lightning/core/module.py:490: UserWarning: You called `self.log('val_mae', ..., logger=True)` but have no logger configured. You can enable one by doing `Trainer(logger=ALogger(...))`
  rank_zero_warn(
/home/mnogales/miniconda3/envs/taming-env/lib/python3.10/site-packages/pytorch_lightning/core/module.py:490: UserWarning: You called `self.log('val_mae_at_3_days', ..., logger=True)` but have no logger configured. You can enable one by doing `Trainer(logger=ALogger(...))`
  rank_zero_warn(
/home/mnogales/miniconda3/envs/taming-env/lib/python3.10/site-packages/pytorch_lightning/core/module.py:490: UserWarning: You called `self.log('val_mae_at_6_days', ..., logger=True)` but have no logger configured. You can enable one by doing `Trainer(logger=ALogger(...))`
  rank_zero_warn(
/home/mnogales/miniconda3/envs/taming-env/lib/python3.10/site-packages/pytorch_lightning/core/module.py:490: UserWarning: You called `self.log('val_mre', ..., logger=True)` but have no logger configured. You can enable one by doing `Trainer(logger=ALogger(...))`
  rank_zero_warn(
/home/mnogales/miniconda3/envs/taming-env/lib/python3.10/site-packages/pytorch_lightning/core/module.py:490: UserWarning: You called `self.log('val_mse', ..., logger=True)` but have no logger configured. You can enable one by doing `Trainer(logger=ALogger(...))`
  rank_zero_warn(
/home/mnogales/miniconda3/envs/taming-env/lib/python3.10/site-packages/pytorch_lightning/core/module.py:490: UserWarning: You called `self.log('val_loss', ..., logger=True)` but have no logger configured. You can enable one by doing `Trainer(logger=ALogger(...))`
  rank_zero_warn(
Epoch 11:  72%|â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–‹         | 41/57 [00:10<00:03,  4.01it/s, val_mae=0.639, val_mae_at_3_days=0.669, val_mae_at_6_days=0.468, val_mre=1.050, val_mse=12.40, train_mae=1.230, train_mae_at_3_days=1.220, train_mae_at_6_days=1.240, train_mre=1.020, train_mse=78.40]
/home/mnogales/miniconda3/envs/taming-env/lib/python3.10/site-packages/pytorch_lightning/core/module.py:490: UserWarning: You called `self.log('train_mae', ..., logger=True)` but have no logger configured. You can enable one by doing `Trainer(logger=ALogger(...))`
  rank_zero_warn(
/home/mnogales/miniconda3/envs/taming-env/lib/python3.10/site-packages/pytorch_lightning/core/module.py:490: UserWarning: You called `self.log('train_mae_at_3_days', ..., logger=True)` but have no logger configured. You can enable one by doing `Trainer(logger=ALogger(...))`
  rank_zero_warn(
/home/mnogales/miniconda3/envs/taming-env/lib/python3.10/site-packages/pytorch_lightning/core/module.py:490: UserWarning: You called `self.log('train_mae_at_6_days', ..., logger=True)` but have no logger configured. You can enable one by doing `Trainer(logger=ALogger(...))`
  rank_zero_warn(
/home/mnogales/miniconda3/envs/taming-env/lib/python3.10/site-packages/pytorch_lightning/core/module.py:490: UserWarning: You called `self.log('train_mre', ..., logger=True)` but have no logger configured. You can enable one by doing `Trainer(logger=ALogger(...))`
  rank_zero_warn(
/home/mnogales/miniconda3/envs/taming-env/lib/python3.10/site-packages/pytorch_lightning/core/module.py:490: UserWarning: You called `self.log('train_mse', ..., logger=True)` but have no logger configured. You can enable one by doing `Trainer(logger=ALogger(...))`
  rank_zero_warn(
/home/mnogales/miniconda3/envs/taming-env/lib/python3.10/site-packages/pytorch_lightning/core/module.py:490: UserWarning: You called `self.log('train_loss', ..., logger=True)` but have no logger configured. You can enable one by doing `Trainer(logger=ALogger(...))`
  rank_zero_warn(
                                                                                                                                                                                                                                                                                        
